# Flutter project metadata
name: vibefinder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  provider: ^6.1.5+1
  geolocator: ^14.0.2
  http: ^1.6.0
  google_maps_flutter: ^2.14.0
  animations: ^2.1.1
  introduction_screen: ^4.0.0
  lottie: ^3.3.2
  google_polyline_algorithm: ^3.1.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true # âœ… Remove transparency for iOS
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#FFFFFF" # set your desired web background
    theme_color: "#50C878"      # primary theme color
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
